version: '3'

includes:
  ansible:
    taskfile: ./ansible/taskfile.yaml
    dir: ./ansible
  packer:
    taskfile: ./packer/taskfile.yaml
    dir: ./packer

tasks:
  help:
    cmds:
      - glow README.md
    silent: true

  cleanup:
    cmds:
      - find ansible/output/cloud-init/ -type f -name '*.cfg' ! -name '99-pve.cfg' -exec rm -rfv {} +
      - find ansible/output/cloud-init/ -type f -name '*-data' -exec rm -rfv {} +
      - find ansible/output/scripts/ -type f -name '*.sh' -exec truncate -s 0 {} +
      - find ansible/output/ssh_keys/ -type f -name 'ssh_key_*' -exec rm -rfv {} +

  template:
    requires:
      vars: [OS_DIST, OS_VERSION, PACKER_API_TOKEN_ID, PACKER_API_TOKEN_SECRET]
    cmds:
      - task: ansible:pre-provisioning
      - task: packer:validate
      - task: packer:init
      - task: packer:build
      - defer: { task: cleanup }
