---
- name: Remove useless packages from the cache
  apt:
    force_apt_get: yes
    autoclean: yes

- name: Remove dependencies that are no longer required
  apt:
    force_apt_get: yes
    autoremove: yes
