---
- name: Upgrade All Packages To The Latest Version
  apt:
    update_cache: yes
    upgrade: yes

- name: Install Core Dependencies, Clean APT, & Remove Old Programs
  apt:
    name: "{{ item }}"
    state: present
    install_recommends: yes
    autoremove: yes
    autoclean: yes
  loop: "{{ packages }}"
