---
- name: Export Vault credentials
  hosts: localhost
  connection: local
  tasks:
    - ansible.builtin.include_tasks: tasks/get_vault_temp_token.yaml
    - ansible.builtin.include_tasks: tasks/export_packer_proxmox_credentials.yaml
