---
- name: Configuring Proxmox cloud-init config
  ansible.builtin.copy:
    content: |
      datasource_list: [ NoCloud, ConfigDrive ]
    dest: /etc/cloud/cloud.cfg.d/99_pve.cfg

- name: Copy cloud-init files for Debian
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - src: "{{playbook_dir}}/../output/cloud-init/cloud.cfg"
      dest: "/etc/cloud/cloud.cfg"
  when: os_dist == "debian"
