template:
  os:
    dist: "debian"
    version: "12"
    codename: "bookworm"
  vm:
    id: "999000012"
    name: "tmpl-debian12"
    template_description: "Debian 12 Bookworm Packer Template"
    cpu_type: "host"
    sockets: "1"
    cores: "2"
    memory: "2048"
  iso:
    file: "nfs-backup-rbx:iso/debian-12.4.0-amd64-netinst.iso"
    url: "https://get.debian.org/images/release/current/amd64/iso-cd/debian-12.4.0-amd64-netinst.iso"
    checksum: "sha512:0262488ce2cec6d95a6c9002cfba8b81ac0d1c29fe7993aa5af30f81cecad3eb66558b9d8689a86b57bf12b8cbeab1e11d128a53356b288d48e339bb003dace5"
    download_pve: true
    storage_pool: "nfs-backup-rbx"
    unmount_iso: true
  packages:
    - apt-transport-https
    - ca-certificates
    - software-properties-common
    - unattended-upgrades
    - gnupg-agent
    - cloud-init
    - cloud-guest-utils
    - cloud-initramfs-growroot
    - locales-all
    - curl
    - btop
    - htop
    - ncdu
    - tmux
    - wget
    - open-iscsi
    - parted
