vm:
  os_dist: "debian"
  os_version: "12"
  id: "999000012"
  name: "tmpl-debian12"
  template_description: "Debian 12 Bookworm Packer Template"
  cpu_type: "host"
  sockets: "1"
  cores: "2"
  memory: "2048"
iso:
  file: "nfs-backup-rbx:iso/debian-12.2.0-amd64-netinst.iso"
  url: "https://get.debian.org/images/release/current/amd64/iso-cd/debian-12.2.0-amd64-netinst.iso"
  checksum: "sha512:11d733d626d1c7d3b20cfcccc516caff2cbc57c81769d56434aab958d4d9b3af59106bc0796252aeefede8353e2582378e08c65e35a36769d5cf673c5444f80e"
  storage_pool: "nfs-backup-rbx"
  unmount_iso: true
cloud_init:
  boot_wait: "5s"
  boot_command: [ "<esc><wait>auto url=http://{{ .HTTPIP }}:{{ .HTTPPort }}/preseed.cfg<enter>" ]
