vm:
  os_dist: "debian"
  os_version: "11"
  id: "999000011"
  name: "tmpl-debian11"
  template_description: "Debian 11 Bullseye Packer Template"
  cpu_type: "host"
  sockets: "1"
  cores: "2"
  memory: "2048"
iso:
  file: "nfs-backup-rbx:iso/debian-11.8.0-amd64-netinst.iso"
  url: "https://cdimage.debian.org/cdimage/archive/11.8.0/amd64/iso-cd/debian-11.8.0-amd64-netinst.iso"
  checksum: "sha512:da7e7867ed043b784f5ae7e4adaaf4f023b5235f0fa2ead1279dc93f74bc17801ed906d330e3cd68ee8d3e96b697d21d23cfe2b755f5a9eb555bd5390a8c4dac"
  storage_pool: "nfs-backup-rbx"
  unmount_iso: true
cloud_init:
  boot_wait: "5s"
  boot_command: [ "<esc><wait>auto url=http://{{ .HTTPIP }}:{{ .HTTPPort }}/preseed.cfg<enter>" ]
