cloud_init:
  boot_wait: "5s"
  boot_command: [
    "<esc><wait><esc><wait><f6><wait><esc><wait>",
    "<bs><bs><bs><bs><bs>",
    "autoinstall ds=nocloud-net;s=http://{{ .HTTPIP }}:{{ .HTTPPort }}/ ",
    "--- <enter>"
  ]
  http_directory: "../ansible/output/cloud-init"
  http_port_min: 8100
  http_port_max: 8100
