vm:
  os_dist: "ubuntu"
  os_version: "2204"
  id: "999002204"
  name: "tmpl-ubuntu2204"
  template_description: "Ubuntu 22.04 Jammy Packer Template"
  cpu_type: "host"
  sockets: "1"
  cores: "2"
  memory: "2048"
iso:
  file: "nfs-backup-rbx:iso/ubuntu-22.04.3-live-server-amd64.iso"
  url: "https://releases.ubuntu.com/jammy/ubuntu-22.04.3-live-server-amd64.iso"
  checksum: "sha512:8e91080603bbae8c92f5102d0c8ddfa05b957965a29e916242c818089734ddc84c24608b9820f895102d06fb5d8b118cc18bf8d60e2a9c20ccd07a8929bba868"
  storage_pool: "nfs-backup-rbx"
  unmount_iso: true
cloud_init:
  boot_wait: "5s"
  boot_command: [
    "<esc><wait>",
    "e<wait>",
    "<down><down><down><end>",
    "<bs><bs><bs><bs><wait>",
    "autoinstall ds=nocloud-net\\;s=http://{{ .HTTPIP }}:{{ .HTTPPort }}/ ---<wait>",
    "<f10><wait>"
  ]
packages:
  - apt-transport-https
  - ca-certificates
  - software-properties-common
  - unattended-upgrades
  - gnupg-agent
  - cloud-init
  - cloud-guest-utils
  - curl
  - htop
  - ncdu
  - tmux
  - wget
