cloud_init:
  boot_wait: "5s"
  boot_command: [
    "<esc><wait>",
    "e<wait>",
    "<down><down><down><end>",
    "<bs><bs><bs><bs><wait>",
    "autoinstall ds=nocloud-net\\;s=http://{{ .HTTPIP }}:{{ .HTTPPort }}/ ---<wait>",
    "<f10><wait>"
  ]
  http_directory: "../ansible/output/cloud-init"
  http_port_min: 8100
  http_port_max: 8100
