vm:
  os_dist: "ubuntu"
  os_version: "2004"
  id: "999002004"
  name: "tmpl-ubuntu2004"
  template_description: "Ubuntu 20.04 Focal Packer Template"
  cpu_type: "host"
  sockets: "1"
  cores: "2"
  memory: "2048"
iso:
  file: "nfs-backup-rbx:iso/ubuntu-20.04.6-live-server-amd64.iso"
  url: "https://releases.ubuntu.com/20.04.6/ubuntu-20.04.6-live-server-amd64.iso"
  checksum: "sha512:1b35a52bd32f5257b3454787c87688fdbe3fdd018a47ed2cf9a7cca71630f54230ceefd544cd984adf7593974b0087a9da2e51eaf9fea8a105ce86ef4be5fc76"
  storage_pool: "nfs-backup-rbx"
  unmount_iso: true
cloud_init:
  boot_wait: "5s"
  boot_command: [
    "<esc><wait><esc><wait><f6><wait><esc><wait>",
    "<bs><bs><bs><bs><bs>",
    "autoinstall ds=nocloud-net;s=http://{{ .HTTPIP }}:{{ .HTTPPort }}/ ",
    "--- <enter>"
  ]
