---
- name: Remove useless packages from the cache
  when: ansible_distribution in ['Debian','Ubuntu']
  ansible.builtin.apt:
    force_apt_get: yes
    autoclean: yes

- name: Remove dependencies that are no longer required
  when: ansible_distribution in ['Debian','Ubuntu']
  ansible.builtin.apt:
    force_apt_get: yes
    autoremove: yes
