---
- name: Get packer credentials
  ansible.builtin.uri:
    url: https://vault.nubiqo.cloud/v1/kv/data/proxmox/packer
    method: GET
    body_format: json
    headers:
      X-Vault-Token: "{{ temp_token }}"
  register: response_credentials

- name: Set variables as facts
  ansible.builtin.set_fact:
     packer_api_token_id : "{{ response_credentials.json.data.data. packer_api_token_id  }}"
     packer_api_token_secret : "{{ response_credentials.json.data.data. packer_api_token_secret  }}"

- name: Export vars to .env file to be populated
  ansible.builtin.blockinfile:
    insertafter: EOF
    marker: "# K3S JOIN TOKEN"
    path: "~/.env"
    block: |
      PACKER_API_TOKEN_ID={{ packer_api_token_id }}
      PACKER_API_TOKEN_SECRET={{ packer_api_token_secret }}
    state: present
    create: true
