---
- name: Generate cloud-init files for Debian
  when: os_dist == "debian"
  ansible.builtin.template:
    src: "{{ os_dist }}/{{ item }}.cfg.j2"
    dest: "{{ playbook_dir }}/../output/cloud-init/{{ os_dist }}/{{ os_version }}/{{ item }}.cfg"
  loop:
    - "cloud"
    - "preseed"

- name: Generate cloud-init files for Ubuntu
  when: os_dist == "ubuntu"
  ansible.builtin.template:
    src: "{{ os_dist }}/{{ item }}.j2"
    dest: "{{ playbook_dir }}/../output/cloud-init/{{ os_dist }}/{{ os_version }}/{{ item }}"
  loop:
    - "user-data"
    - "meta-data"
